class CareerRepository {
  static List<String> careers = [
    "Administração",
    "Análise de Dados",
    "Anatomia",
    "Arquitetura",
    "Assistência Social",
    "Atendimento ao Cliente",
    "Biologia",
    "Biomedicina",
    "Ciência da Computação",
    "Ciências Ambientais",
    "Comércio Exterior",
    "Comunicação",
    "Contabilidade",
    "Design",
    "Desenvolvimento de Produtos",
    "Direito",
    "Economia",
    "Educação",
    "Educação Física",
    "Enfermagem",
    "Engenharia",
    "Engenharia Civil",
    "Engenharia de Software",
    "Engenharia Mecânica",
    "Estatística",
    "Estética",
    "Estudante",
    "Farmácia",
    "Finanças",
    "Fisioterapia",
    "Gestão de Projetos",
    "Logística",
    "Marketing",
    "Medicina",
    "Nutrição",
    "Odontologia",
    "Planejamento",
    "Pesquisa",
    "Produção",
    "Psicologia",
    "Publicidade",
    "Recursos Humanos",
    "Relações Públicas",
    "Saúde",
    "Tecnologia da Informação",
    "Terapia Ocupacional",
    "Vendas",
    "Veterinária",
    "Outro",
  ];
}
