class CourseRepository {
  static List<String> courses = [
    "Administração",
    "Análise e Desenvolvimento de Sistemas",
    "Antropologia",
    "Arquitetura e Urbanismo",
    "Biologia",
    "Biblioteconomia",
    "Ciência de Dados",
    "Ciências Atuariais",
    "Ciências Biológicas",
    "Ciências Contábeis",
    "Ciências Econômicas",
    "Design",
    "Design Gráfico",
    "Direito",
    "Economia",
    "Educação Física",
    "Enfermagem",
    "Engenharia Ambiental",
    "Engenharia Civil",
    "Engenharia de Alimentos",
    "Engenharia de Produção",
    "Engenharia de Software",
    "Engenharia de Telecomunicações",
    "Engenharia Elétrica",
    "Engenharia Mecânica",
    "Engenharia Química",
    "Fisioterapia",
    "Física",
    "Farmácia",
    "Geografia",
    "Gestão de Projetos",
    "Gestão de Recursos Humanos",
    "Gestão de Tecnologia da Informação",
    "História",
    "Jornalismo",
    "Letras",
    "Logística",
    "Marketing",
    "Matemática",
    "Medicina",
    "Nutrição",
    "Odontologia",
    "Pedagogia",
    "Publicidade e Propaganda",
    "Psicologia",
    "Rádio e TV",
    "Relações Internacionais",
    "Sociologia",
    "Serviço Social",
    "Turismo",
    "Veterinária",
    "Zootecnia",
    "Outro",
    "Nenhum",
  ];
}
