// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIrJlyA0eirMAl-GElWtonwVMudRU2Ndg',
    appId: '1:344212920689:web:c992b9eb94d586a0b17ed0',
    messagingSenderId: '344212920689',
    projectId: 'aiesecmembercheck',
    authDomain: 'aiesecmembercheck.firebaseapp.com',
    storageBucket: 'aiesecmembercheck.appspot.com',
    measurementId: 'G-RMMXFZDQWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChVBaeDvPXyvCRSNU4_pV9TyEj1QjZC0U',
    appId: '1:344212920689:android:82a60fb84d6b6192b17ed0',
    messagingSenderId: '344212920689',
    projectId: 'aiesecmembercheck',
    storageBucket: 'aiesecmembercheck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbEuf0bE2QQdx14rvDlVsFEIfWHlFyiFQ',
    appId: '1:344212920689:ios:1c3e78502740d8d0b17ed0',
    messagingSenderId: '344212920689',
    projectId: 'aiesecmembercheck',
    storageBucket: 'aiesecmembercheck.appspot.com',
    iosBundleId: 'com.example.aiesecmembercheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbEuf0bE2QQdx14rvDlVsFEIfWHlFyiFQ',
    appId: '1:344212920689:ios:1c3e78502740d8d0b17ed0',
    messagingSenderId: '344212920689',
    projectId: 'aiesecmembercheck',
    storageBucket: 'aiesecmembercheck.appspot.com',
    iosBundleId: 'com.example.aiesecmembercheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIrJlyA0eirMAl-GElWtonwVMudRU2Ndg',
    appId: '1:344212920689:web:094499c436402250b17ed0',
    messagingSenderId: '344212920689',
    projectId: 'aiesecmembercheck',
    authDomain: 'aiesecmembercheck.firebaseapp.com',
    storageBucket: 'aiesecmembercheck.appspot.com',
    measurementId: 'G-C8P4YDRMKH',
  );
}
